---
- name: Let's copy our executable script to remote location, execute script and get result back.
  user: directfn
  hosts: host
  tasks:
  remote_src: true
     - name: Transfer executable script script
       copy: src=start_falcon_server.sh dest=/home/directfn/start/ mode=0777
 
     - name: Execute the script
       command: sh -c "/home/directfn/start/start_falcon_server.sh --param1 'param1' "
     
