---
- name: Let's copy our executable script to remote location, execute script and get result back.
  user: directfn
  hosts: host
  tasks:
     - name: Execute the script
       command: sh -c "/home/directfn/start-stop/start_falcon_server.sh"
     - name: Execute the script with args 
       command: sh -c "/home/directfn/scripts/manager.sh --param1 'param1' "
     
