---
- hosts: host
  gather_facts: no
  tasks:
  - name: Download Tomcat
    get_url: url=wget --no-check-certificate https://viraj:AP5NFbRipQFuJrozbggriZ5FDgg@jfrog.directfn.net/artifactory/ntp_utils/java_1.8.121/jdk1.8.0_121.tgz dest=/home

  - name: Extract the file downloaded tomcat file
    command: tar xvf apache-tomcat-8.5.32.tar.gz
 
  - name: Move the Tomcat directory to a smaller one
    command: mv apache-tomcat-8.5.32 tomcat
