---
- hosts: host
  gather_facts: no
  tasks:
  - name: Download Tomcat
    get_url: url=https://viraj:AP5NFbRipQFuJrozbggriZ5FDgg@jfrog.directfn.net/artifactory/ntp_utils/java_1.8.121/jdk1.8.0_121.tgz dest=/home/directfn/app

  - name: Extract the file downloaded tomcat file
    command: tar xvf jdk1.8.0_121.tgz
 
  - name: Move the Tomcat directory to a smaller one
    command: mv jdk1.8.0_121 jdk1.8
